---
title: "annual plants are cool"
format: html
editor: visual
---

```{r}
install.packages("tidyverse")
devtools::install_github("traitecoevo/austraits")
library(tidyverse)
library(austraits)
austraits <- load_austraits(version = "4.1.0", path = "intro/downloads")

```

```{r}
#extract life history traits
annual_perennial_traits <- austraits %>% extract_trait('life_history')

#down with tibbles
annual_perennial_traits <- left_join(annual_perennial_traits[["traits"]], annual_perennial_traits[["taxa"]], by = "taxon_name")

#unique taxa with life history traits
length(unique(annual_perennial_traits$taxon_name))
#28332

#different life history values
unique(annual_perennial_traits$value)
# [1] "perennial"                                       "biennial perennial"       # [3] "annual"                                          "annual perennial"         # [5] "biennial"                                        "annual biennial"          # [7] "annual short_lived_perennial"                    "ephemeral"                # [9] "short_lived_perennial"                           "annual ephemeral"        #[11] "annual biennial perennial"                       "biennial short_lived_perennial"                 
#[13] "annual ephemeral perennial"                      "annual biennial short_lived_perennial"          
#[15] "perennial short_lived_perennial"                 "biennial perennial short_lived_perennial"       
#[17] "annual perennial short_lived_perennial"          "ephemeral short_lived_perennial"                
#[19] "ephemeral perennial"                             "annual biennial perennial short_lived_perennial"
#surely a 'ephemeral perennial short lived perennial is an annual????

annual_trait <- unique(annual_perennial_traits$value[grepl("annual", annual_perennial_traits$value)])


#number of records with 'annual' value
sum(annual_perennial_traits$value %in% annual_trait)
#12441

#records of annuals
annual_species_data <- subset(annual_perennial_traits, value %in% annual_trait)

#unique taxa with at least one record of annual life history form
length(unique(annual_species_data$taxon_name))
#4427

```

```{r}
install.packages("galah")
install.packages("remotes")
remotes::install_github("AtlasOfLivingAustralia/galah")

galah_config(email = 'adelegemmell@hotmail.com')

```

```{r}

```
