---
title: "fire_ephemerals"
format:
  html:
    embed-resources: true
editor: visual
execute:
  warning: false
  output: true
---

## Fire Ephemerals

Load NSW Fire dataset

```{r}
#install.packages("pacman")
#pacman::p_load(tidyverse, here, rmapshaper, sf, ggpointdensity, viridis, ozmaps, concaveman, cowplot, patchwork)
library(maps)
library(mapdata)
library(tidyverse)
library(sf)
library(extrafont)
library(here)
library(ozmaps)
library(ggthemes)
library(galah)

fire <- st_read(here("NPWS_fire", "NPWSFireHistory.shp")) |> 
  st_transform(crs = 4326) |> 
  st_zm()  # Remove Z or M values

#add start year
fire$StartYear <- substr(fire$StartDate, 1, 4)

#some fires have an arbitary 'start year' of 1899 where the start date is unknown, even if they are labelled as '1996-97 wildfire'. replace start year for these records with the year given in the 'Label' field. The fire dataset begins in 1902

fire <-  fire %>%
  mutate(StartYear = ifelse(is.na(StartYear) | StartYear == '1899', substr(Label, 1, 4), StartYear))

#create nswv polygon
sf_oz <- ozmap_data("states") |>
  st_transform(crs = 4326)

nsw <- sf_oz %>%
  filter(NAME == 'New South Wales')

```

## Get distribution data on fire ephemerals in NSW

```{r}
#based on https://www.anpc.asn.au/wp-content/uploads/2022/07/APC_30-2_Sept-Nov21_Bell-v1.pdf, some NSW fire ephemerals include Actinotus forsythii, Monotaxis macrophylla (endangered), Gyrostemon australasicus, Gyrostemon thesioides (endangered), Androcalva procumbens (vulnerable), Androcalva rosea (endangered), Commersonia rugosa 



galah_config(email = 'adelegemmell@hotmail.com')

show_all_fields() |>
  View()

search_fields('status') |>
  View()

fire_ephemerals <- galah_call() |>
  galah_identify('Actinotus forsythii', 'Monotaxis macrophylla', 'Gyrostemon australasicus', 'Gyrostemon thesioides', 'Androcalva procumbens', 'Androcalva rosea', 'Commersonia rugosa') |>
  galah_filter(cl22 == 'New South Wales') |>
  galah_apply_profile(ALA) |>
  atlas_occurrences()

select <- c(colnames(fire_ephemerals)[1:8], "countryConservation", "stateConservation")
  
fire_ephemerals <- galah_call() |>
  galah_identify('Actinotus forsythii', 'Monotaxis macrophylla', 'Gyrostemon australasicus', 'Gyrostemon thesioides', 'Androcalva procumbens', 'Androcalva rosea', 'Commersonia rugosa') |>
  galah_filter(cl22 == 'New South Wales') |>
  galah_select(select) |>
  galah_apply_profile(ALA) |>
  atlas_occurrences()

fire_ephemerals %>% 
  group_by(scientificName) %>%
  summarise(count = n())

fire_ephemerals$year <- substr(fire_ephemerals$eventDate, 1, 4)

fire_ephemerals$month <- substr(fire_ephemerals$eventDate, 6, 7)

fire_ephemerals$month <- as.numeric(fire_ephemerals$month)

fire_ephemerals$months <- month.name[(fire_ephemerals$month)]

fire_ephemerals$months <- factor(fire_ephemerals$months, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"))
```

## Map fire ephemerals in NSW

```{r}
ggplot() +
  geom_sf(data = nsw,
          fill = NA,
          colour = "grey60") +
  geom_point(data = fire_ephemerals,
             aes(x = decimalLongitude,
                 y = decimalLatitude,
                 color = scientificName)) +
  labs(color = 'Species') +
  theme_void()
```

## Map against fire history

```{r}
#remove records of ephemerals from before 1902 as they do not crossover with fire data
fire_ephemerals <- fire_ephemerals %>%
  filter(year > 1901)

fire <- st_make_valid(fire)

fire_within_nsw <- st_intersection(fire, nsw)

ggplot() +
  geom_sf(data = nsw,
          fill = 'beige',
          colour = "darkgrey") +
  geom_sf(data = fire_within_nsw,
          colour = '#FF5A0080',
          fill = '#FF5A0020') +
  geom_point(data = fire_ephemerals,
             aes(x = decimalLongitude,
                 y = decimalLatitude,
                 color = scientificName)) +
  labs(title = 'Fire history and fire ephemeral species in NSW', color = 'Species') +
  scale_color_brewer(palette = 'Set1') +
  theme_map() +
  theme(plot.background = element_rect(fill = "white", color = NA),
        text = element_text(family = "Arial"),
        legend.position = "right",
        plot.title = element_text(size = 15, hjust = 0.5))

ggsave('maps_graphs/ephemerals_nsw_map.png')


```

## Area burnt each year v records

```{r}

#font_import()
#loadfonts()

#fire ephemeral records by year
obs_year <- fire_ephemerals %>% 
  group_by(scientificName, year) %>%
  summarise(count = n())

#only 1 Gyrostemon australasicus	record in NSW after 2000
obs_year_recent <- obs_year %>%
  filter(year > 1999, scientificName != 'Gyrostemon australasicus') 

obs_year_recent %>%
  group_by(scientificName) %>%
  summarise(count = n())


area_year <- fire %>%
  group_by(StartYear) %>%
  summarize(sum(AreaHa))

area_year_recent <- area_year %>%
filter(StartYear > 1999) %>%
  st_drop_geometry() %>%
  as.data.frame()

names(area_year_recent)[2] <- "AreaHa"

obs_fire <-  ggplot() +
  geom_bar(data = obs_year_recent[obs_year_recent$year > 2012, ], aes(fill = scientificName, y = count, x = year), position = "dodge", stat = "identity") +
  geom_line(data = area_year_recent[area_year_recent$StartYear > 2012, ], aes(x = StartYear, y = AreaHa/18000, group = 1), size = 1, alpha = 0.7) +
  labs(title = 'Fire area & fire ephemerals observations in NSW', fill = 'Species') +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(), axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(name = "Observations", sec.axis = sec_axis(trans = ~.*18000, 
                        name = 'Area Burnt (ha)',
                        labels = scales::number_format(scale = 1, accuracy = 1),
                        breaks = seq(0, 5000000, by = 1000000))) 


obs_fire

ggsave('maps_graphs/obs_fires.png')
```

```{r}

library(ggpointdensity)
library(ggplot2)
library(viridis)

ggplot() +
  geom_sf(data = nsw,
          fill = 'beige',
          colour = "darkgrey") +
  geom_sf(data = fire_within_nsw,
          colour = '#FF5A0080',
          fill = '#FF5A0020') +
  geom_pointdensity(data = fire_ephemerals,
             aes(x = decimalLongitude,
                 y = decimalLatitude)) +
  labs(title = 'Fire history and fire ephemerals in NSW', color = 'Observations') +
  scale_color_gradient(high = '#05450e', low = '#30d148') + 
  theme_map() +
  theme(plot.background = element_rect(fill = "white", color = NA),
        legend.position = "right",
        text = element_text(family = "Arial", size = 16))

ggsave('maps_graphs/ephemeral_density.png')

ggplot() +
  geom_sf(data = nsw,
          fill = 'beige',
          colour = "darkgrey") +
  geom_sf(data = fire_within_nsw,
          colour = '#FF5A0080',
          fill = '#FF5A0020') +
  stat_density_2d(data = fire_ephemerals,
                 contour = TRUE,
             aes(x = decimalLongitude,
                 y = decimalLatitude,
                 fill = after_stat(level),
                  bins = 5),
             geom = 'polygon',
             alpha = 0.5) +
  labs(title = 'Fire history and fire ephemerals in NSW', fill = 'Density') +
  scale_fill_viridis() + 
  theme_map() +
  theme(plot.background = element_rect(fill = "white", color = NA),
        legend.position = "right",
        text = element_text(family = "Arial", size = 14))

```

```{r}
fire_ephemerals %>%
  filter(year > 1999) %>%
ggplot() +
  geom_bar(aes(x = year, fill = dataResourceName)) +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(), axis.text.x = element_text(angle = 90, hjust = 1))


fire_ephemerals %>%
  filter(year > 1999) %>%
  group_by(dataResourceName, scientificName) %>%
  summarise(count = n()) |>
  arrange(desc(count))


data_count <- fire_ephemerals %>%
  filter(year > 1999) %>%
  group_by(dataResourceName) %>%
  summarise(count = n()) |>
  arrange(desc(count))

top_4 <- data_count$dataResourceName[1:4]

fire_ephemerals %>%
  filter(year > 2012) %>%
  mutate(dataResourceCategory = ifelse(dataResourceName %in% top_4, as.character(dataResourceName), "Other")) %>%
  mutate(dataResourceCategory = factor(dataResourceCategory, levels = c(top_4, "Other"))) %>%
  ggplot() +
  geom_bar(aes(x = year, fill = dataResourceCategory)) +
  labs(x = 'Year', y = 'Observations', fill = 'Source') +
  theme_fivethirtyeight() +
  theme(axis.title = element_text(), axis.text.x = element_text(angle = 90, hjust = 1)) +
  guides(fill = guide_legend(ncol = 2))

ggsave('maps_graphs/obs_source_2013.png')
```

```{r}
fire_ephemerals %>%
  filter(year > 2012) %>%
  mutate(dataResourceCategory = ifelse(dataResourceName %in% top_4, as.character(dataResourceName), "Other")) %>%
  mutate(dataResourceCategory = factor(dataResourceCategory, levels = c(top_4, "Other"))) %>%
  ggplot() +
  geom_bar(aes(x = str_wrap(scientificName, width = 15), fill = dataResourceCategory)) +
  labs(x = 'Year', y = 'Observations', fill = 'Source') +
  theme_fivethirtyeight() +
  theme(axis.title = element_text()) +
  guides(fill = guide_legend(ncol = 2)) 

```

```{r}
#country conservation
fire_ephemerals %>%
  filter(year > 2012) %>%
  ggplot() +
  geom_bar(aes(x = countryConservation, fill = scientificName)) +
  theme_classic()

#state conservation 
fire_ephemerals %>%
  filter(year > 2012) %>%
  ggplot() +
  geom_bar(aes(x = stateConservation, fill = scientificName)) +
  theme_classic()


```

```{r}



```

```{r}
```
